version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gradle"
    target-branch: "8.8.x"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    target-branch: "8.7.x"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    target-branch: "8.6.x"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    target-branch: "8.5.x"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    target-branch: "8.4.x"
    directory: "/"
    schedule:
      interval: "daily"
